# Generated by Django 3.1.5 on 2021-01-24 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210114_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='title',
        ),
    ]
